---
# tasks file for angular
- name: Ensure Chocolatey installed from internal repo
  win_chocolatey:
    name: chocolatey
    state: present
    source: http://internal/odata/repo/ChocolateyInstall.ps1
	
- name: Ensure nodejs-lts installed
  win_chocolatey:
    name: nodejs-lts
    state: present
    version: 14.16.1
    source: http://internal/odata/repo
	
- name: Install Angular.js
  npm:
    name: "@angular/cli@8.3.19"
    global: yes
    state: present
